name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: 1.22.2

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u qjoly --password-stdin

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0
        with:
          cosign-release: 'v2.4.0'

      - uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sign container image
        run: |
            docker pull ghcr.io/qjoly/alertmanager-awtrix/alertmanager-awtrix:${GITHUB_REF#refs/*/} 
            export DOCKER_FULL_SHA=$(docker inspect ghcr.io/qjoly/alertmanager-awtrix/alertmanager-awtrix:${GITHUB_REF#refs/*/} | jq -r '.[0].RepoDigests[0]')
            echo "SHA: $DOCKER_FULL_SHA"
            cosign sign --yes --key env://COSIGN_PRIVATE $DOCKER_FULL_SHA
        shell: bash
        env:
          COSIGN_PRIVATE: ${{secrets.COSIGN_PRIVATE}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

